# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: ["main"]

jobs:
  lint-and-scan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: With NodeJs V20
      uses: actions/setup-node@v4
      with:
        node-version; 20.x

    - name: Install Deps
      run: npm ci
      working-directory: ./frontend
    
    - name: Run Lint
      run: npm run lint
      working-directory: ./frontend
    
    - name: Run CodeQL analysis
      uses: github/codeql-action/init@v2
      with:
        languages: javascript
    - uses: github/codeql-action/analyze@v2


  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependancies and build
      run: |
        npm ci
        npm run build
      working-directory: ./backend

    - name: Restart pm2
      run: pm2 restart warboard-be
